/*
 * Copyright (c) 2025-2030 Centimia Ltd.
 * All rights reserved.  Unpublished -- rights reserved
 *
 * Use of a copyright notice is precautionary only, and does
 * not imply publication or disclosure.
 *
 * Licensed under Eclipse Public License, Version 2.0,
 * Initial Developer: Shai Bentin, Centimia Ltd.
 */

/*
 * Update Log
 *
 *  Date			User				Comment
 * ------			-------				--------
 * 07/02/2010		Shai Bentin			 create
 */
package com.centimia.orm.ezqu;

/**
 * Type of generator Ezqu supports for primary keys on Entities.
 *
 * @author Shai Bentin
 */
public enum GeneratorType {
	/** USe for generating the id using a sequence. Use the sequence name to tell EzQu which sequence to use */
	SEQUENCE,

	/** For auto increment fields. In this strategy the id is generated by the underlying db. EzQu returns the keys in the objects */
	IDENTITY,

	/** EzQu will generate the id using a UUID pattern. Apply this strategy to java.lang.String type, or {@link java.util.UUID} type */
	UUID,

	/** EzQu expects that the developer will supply a unique primary key. This is the default */
	NONE;
}
